#!/bin/bash

set -o xtrace

TRANSLATION=$1
REFERENCE=$2
LANGUAGE=$3
NAME=$4

UDPIPE_DIR=~rosa/himl/autohume/udpipe
UDPIPE="$UDPIPE_DIR/udpipe --tag --parse --input=horizontal $UDPIPE_DIR/models/$LANGUAGE.udpipe"

# tag and parse the reference
if [ ! -s $NAME/reference.conllu ]
then
    cat $REFERENCE   | $UDPIPE | grep -v '^#' > $NAME/reference.conllu
fi
if [ ! -s $NAME/translation.conllu ]
then
    cat $TRANSLATION | $UDPIPE | grep -v '^#' > $NAME/translation.conllu
fi

# align the translation and the reference
if [ ! -s $NAME/alignment ]
then
    scripts/monolingual_alignment.pl $NAME/reference.conllu $NAME/translation.conllu > $NAME/alignment
fi

# generate aligned subtrees
scripts/get_parallel_subtrees.pl --ref-trees $NAME/reference.conllu --alignment $NAME/alignment --translation $TRANSLATION > $NAME/parallel_subtrees

cat $NAME/parallel_subtrees | cut -f3 > $NAME/ref_subtrees
cat $NAME/parallel_subtrees | cut -f4 > $NAME/trans_subtrees
scripts/chrF.py --ref $NAME/ref_subtrees --hyp $NAME/trans_subtrees --beta 3 --ngram 6 > $NAME/subtrees.chrF 

paste $NAME/parallel_subtrees $NAME/subtrees.chrF | scripts/compute_autohume.pl > $NAME/autohume.score



