#!/bin/bash

set -o xtrace

for l in cs de pl ro; do
    echo Language: $l
    DIR=autohume_predictions/himl15/$l
    mkdir -p $DIR
    sys=data/himl2015/himl2015.en-$l.trans
    ref=data/himl2015/himl2015.en-$l.ref
    autohume $sys $ref $l $DIR
    scripts/chrF.py --hyp $sys --ref $ref --beta 3 --ngram 6 > $DIR/sentences.chrF 
    ucca=data/himl2015/himl2015.en-$l.ucca
    echo Autohume: `paste $DIR/autohume.score $ucca | scripts/pearson.pl`
    echo SentCHRF: `paste $DIR/sentences.chrF $ucca | scripts/pearson.pl`
done

